apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-controller


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-controller
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-controller
subjects:
  - kind: ServiceAccount
    name: vector-controller # name of your service account
    namespace: default # this is the namespace your service account is in
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: vector-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-controller
  template:
    metadata:
      labels:
        app: vector-controller
    spec:
      serviceAccountName: vector-controller
      containers:
        - name: vector-controller
          image: "wangyikewyk/vector-controller:0.1.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP

