apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-controller


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-controller
rules:
  - apiGroups: ["v1"]
    resources: ["configmaps"]
    verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-controller
subjects:
  - kind: ServiceAccount
    name: vector-controller # name of your service account
    namespace: default # this is the namespace your service account is in
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: vector-controller
  apiGroup: rbac.authorization.k8s.io